- hosts: redpanda

  tasks:
  - name: Copy CA Certs
    copy:
      src: tls/ca/ca.crt
      dest: "{{ redpanda_truststore_file }}"
      owner: redpanda
      group: redpanda
      force: "{{ overwrite_certs | default('no') | bool }}"

  - name: Copy Node Certs
    copy:
      src: tls/certs/{{ansible_hostname}}/node.crt
      dest: "{{ redpanda_cert_file }}"
      owner: redpanda
      group: redpanda
      force: "{{ overwrite_certs | default('no') | bool }}"

  - name: Set Redpanda config
    set_fact:
      tls: true

  - name: Apply updated config via reapplying the redpanda_broker role
    import_role:
      name: redpanda_broker
    when: not skip_node | default(false) | bool
