- import_playbook: install-node-deps.yml

- import_playbook: prepare-data-dir.yml

- hosts: redpanda
  roles:
    - role: redpanda_broker
      when: not skip_node | default(false) | bool

- import_playbook: deploy-prometheus-grafana.yml